### PR TITLE
Symmetrical Mod Fixes and Updates

### LINKED ISSUE #18: STL Fix ?
[BFI_Front_with_logo_M3_symetrical_x2.stl](https://github.com/clee/VoronBFI/blob/main/usermods/Tetsu/Symetrical%20BFI/STLs/BFI_Front_with_logo_M3_symetrical_x2.stl)

The included STL is without logo

### PR DESCRIPTION
**Pull request by ndanyluk**
Hi @Clee!

I took a stab at making some updates and fixes to the symmetrical mod by @Tetsu97.

Updates:

* Adds 5x18mm pin carriers (to maintain compatibility with normal BFI)
* Re-orients the parts for printing
* Fixes naming of parts to match base mod & Voron style
* Fixes the missing logo on the M3 Symmetrical BFI Front
* Updates the usermod readme

This should hopefully close #18 & #20.

Let me know if you need any changes or updates and I'd be happy to make em.  Sorry also if this is overstepping, I had already made these fixes for my V2 and figured I'd share em back.

Best,
Nick

### CODE REVIEW

**Comment by clee** [comment]
Hi @ndanyluk! This is awesome.

As long as @tetsu97 is fine with these changes, I'm good with them!

**Comment by tetsu97** [comment]
Hi @ndanyluk !
Looks okay! Thank you very much. Honestly, I completely forgot about it so I'm glad someone took care of it.

**Comment by orangetruth** [comment]
@ndanyluk even though I can see the logo on the logo version in Tinkercad, it doesn't slice in SuperSlicer and it looks completely flat on Github. It didn't look right in F360 either, but it worked after uploading to Tinkercad and downloading again.
image
image
image

**Comment by ndanyluk** [comment]
@orangetruth quick question, in Superslicer did you select "split to parts" after right clicking on the model?

The usual method is to right click, split to parts then delete or change the color of the logo pieces as needed.

I was able to slice this in Superslicer and print for my V2 but I'll double check I didn't mess it up when I re-oriented the part.

**Comment by ndanyluk** [comment]
> @ndanyluk even though I can see the logo on the logo version in Tinkercad, it doesn't slice in SuperSlicer and it looks completely flat on Github. It didn't look right in F360 either, but it worked after uploading to Tinkercad and downloading again. image image image

Hi @orangetruth so I took a look and it seems that the parts are correct, but need to follow the process I mentioned above.  You can see in this screenshot that the logo is there but extremely faint. Slicing as-is will result in what you see in your screenshots.

image

image

image

image

**Comment by orangetruth** [comment]
@ndanyluk Ah, I didn't realize that was an option! Yes, that works, thank you!

**Pull request merged**
